# Following the documentation for Docker usage here:
# https://docs.travis-ci.com/user/docker/
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release
